# Build pipeline will run whenever a pull request is raised on a feature branch
name: Build

on:
  pull_request:
    types:
      - opened
    branches:
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      
      - name: Install dependencies
        run: npm install
        
      - name: Code Linting
        run: npm run lint

      - name: Unit Testing
        run: npm run test
      
      - name: Build Angular app
        run: npm run build-prod
