# Deploy pipeline will trigger whenever Pull request is merged to main branch
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      
      - name: Install dependencies
        run: npm install
        
      #- name: Code Linting
      #  run: npm run lint

      #- name: Unit Testing
      #  run: npm run test
      
      - name: Build Angular app
        run: npm run build-prod
        
      - name: ftp-action
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: coderlab.k2key.in
          # FTP user
          user: cicdpoc
          # FTP password
          password: 56*Lzxk75
          # Force SSL encryption
          forceSsl: false # optional, default is false
          # Local directory
          localDir: ./dist
          # Remote directory
          remoteDir: C:\inetpub\vhosts\coderlab.k2key.in\democoderlab.k2key.in\ci-cd-poc\
